/**
 * Leg geometry for the maps. When `src/data/geo/legs.ts` has a road-snapped line for a leg
 * (generated by `npm run snap-legs`), the maps draw it; otherwise they fall back to a straight
 * line between the two stops. Pure functions only — no Leaflet here.
 */

export type LatLng = [number, number];

/** Legs are stored once, in clockwise order, keyed "from>to". */
export function legKey(from: string, to: string): string {
  return `${from}>${to}`;
}

/** Decode a Google encoded polyline (precision 5, as returned by OSRM `geometries=polyline`). */
export function decodePolyline(str: string, precision = 5): LatLng[] {
  const factor = 10 ** precision;
  const out: LatLng[] = [];
  let i = 0;
  let lat = 0;
  let lng = 0;
  const next = () => {
    let result = 0;
    let shift = 0;
    let b: number;
    do {
      b = str.charCodeAt(i++) - 63;
      result |= (b & 0x1f) << shift;
      shift += 5;
    } while (b >= 0x20 && i <= str.length);
    return result & 1 ? ~(result >> 1) : result >> 1;
  };
  while (i < str.length) {
    lat += next();
    lng += next();
    out.push([lat / factor, lng / factor]);
  }
  return out;
}

export function encodePolyline(points: LatLng[], precision = 5): string {
  const factor = 10 ** precision;
  let out = '';
  let pLat = 0;
  let pLng = 0;
  const put = (v: number) => {
    let n = v < 0 ? ~(v << 1) : v << 1;
    while (n >= 0x20) {
      out += String.fromCharCode((0x20 | (n & 0x1f)) + 63);
      n >>= 5;
    }
    out += String.fromCharCode(n + 63);
  };
  for (const [lat, lng] of points) {
    const iLat = Math.round(lat * factor);
    const iLng = Math.round(lng * factor);
    put(iLat - pLat);
    put(iLng - pLng);
    pLat = iLat;
    pLng = iLng;
  }
  return out;
}

/** Douglas–Peucker simplification; `tolerance` in degrees (0.0005 ≈ 50 m). Keeps both ends. */
export function simplify(points: LatLng[], tolerance: number): LatLng[] {
  if (points.length < 3) return points.slice();
  const keep = new Uint8Array(points.length);
  keep[0] = keep[points.length - 1] = 1;
  const stack: [number, number][] = [[0, points.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop()!;
    let maxD = 0;
    let idx = -1;
    for (let i = a + 1; i < b; i++) {
      const d = segmentDistance(points[i], points[a], points[b]);
      if (d > maxD) {
        maxD = d;
        idx = i;
      }
    }
    if (idx >= 0 && maxD > tolerance) {
      keep[idx] = 1;
      stack.push([a, idx], [idx, b]);
    }
  }
  return points.filter((_, i) => keep[i]);
}

function segmentDistance(p: LatLng, a: LatLng, b: LatLng): number {
  const dx = b[0] - a[0];
  const dy = b[1] - a[1];
  const len2 = dx * dx + dy * dy;
  const t = len2 ? Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / len2)) : 0;
  return Math.hypot(p[0] - (a[0] + t * dx), p[1] - (a[1] + t * dy));
}

/** Great-circle distance in km. */
export function haversineKm(a: LatLng, b: LatLng): number {
  const r = (d: number) => (d * Math.PI) / 180;
  const h = Math.sin(r(b[0] - a[0]) / 2) ** 2 + Math.cos(r(a[0])) * Math.cos(r(b[0])) * Math.sin(r(b[1] - a[1]) / 2) ** 2;
  return 2 * 6371 * Math.asin(Math.sqrt(h));
}

export function pathKm(points: LatLng[]): number {
  let km = 0;
  for (let i = 1; i < points.length; i++) km += haversineKm(points[i - 1], points[i]);
  return km;
}

/**
 * Line for one leg: the snapped geometry (reversed for counter-clockwise travel) or a straight
 * line between the stops. Returns [] if a stop is unknown.
 */
export function legPath(from: string, to: string, stops: Record<string, { lat: number; lng: number }>, legs: Record<string, string>): LatLng[] {
  const a = stops[from];
  const b = stops[to];
  if (!a || !b) return [];
  const fwd = legs[legKey(from, to)];
  if (fwd) return decodePolyline(fwd);
  const back = legs[legKey(to, from)];
  if (back) return decodePolyline(back).reverse();
  return [
    [a.lat, a.lng],
    [b.lat, b.lng],
  ];
}

/** One continuous line through consecutive stops. */
export function pathThrough(ids: string[], stops: Record<string, { lat: number; lng: number }>, legs: Record<string, string>): LatLng[] {
  const out: LatLng[] = [];
  for (let i = 0; i < ids.length - 1; i++) {
    const seg = legPath(ids[i], ids[i + 1], stops, legs);
    out.push(...(out.length ? seg.slice(1) : seg));
  }
  if (ids.length === 1 && stops[ids[0]]) out.push([stops[ids[0]].lat, stops[ids[0]].lng]);
  return out;
}
