/**
 * Checks a leg's map line against Taiwan's scooter rules and against the roads the data says it takes.
 * Pure: the road segments come from src/data/geo/legRoads.ts (generated by `npm run snap-legs`), the rules
 * from src/data/scooterRules.ts.
 */
// `.ts` extension so scripts/snap-legs.ts can load this under Node's built-in TypeScript support.
import { parseRoads } from './roads.ts';

/** A run of the map line along one road, as reported by Valhalla map-matching. */
export interface RoadSeg {
  /** OSM names and refs, e.g. ["蘇花路一段", "9丁", "台9丁線"]. */
  names: string[];
  /** OSM road class: motorway, trunk, primary, secondary, tertiary, unclassified, residential, service… */
  cls: string;
  km: number;
  tunnel?: boolean;
  /** Where the run starts: latitude (for rules limited to a stretch of coast, like the Suhua) and longitude. */
  lat: number;
  lng: number;
}

export interface ScooterRule {
  id: string;
  /** Short description shown in failures, e.g. "Expressway (快速公路 / 高架)". */
  label: string;
  reason: string;
  source: string;
  checked: string;
  bans: (s: RoadSeg) => boolean;
  /** Roads the rule would catch that scooters may in fact use. */
  allows?: (s: RoadSeg) => boolean;
}

export interface Violation {
  rule: ScooterRule;
  seg: RoadSeg;
}

export function violations(segs: RoadSeg[], rules: ScooterRule[]): Violation[] {
  const out: Violation[] = [];
  for (const seg of segs) {
    for (const rule of rules) {
      if (rule.bans(seg) && !rule.allows?.(seg)) out.push({ rule, seg });
    }
  }
  return out;
}

// OSM refs come as "9丁", "台9丁線", "106", "縣道106", "市道106", "花64" (county-prefixed)…; reduce them to "9丁" / "106" / "64".
function normRef(token: string): string {
  return token
    .replace(/^(台|臺|縣道|市道|省道)/, '')
    .replace(/^[\u4e00-\u9fff](?=\d)/, '')
    .replace(/(線|號)$/, '');
}

/** The refs a data road string names, in OSM form: "Tai 9D / County 122" → ["9丁", "122"]. */
export function namedRefs(road: string): string[] {
  return parseRoads(road)
    .filter((r) => r.kind !== 'other')
    .map((r) => normRef(r.zh));
}

export function onRoad(seg: RoadSeg, refs: string[]): boolean {
  return seg.names.some((n) => refs.includes(normRef(n)));
}

/** Share (0–1) of the line's distance that is on one of the roads the data names. */
export function namedShare(road: string, segs: RoadSeg[]): number {
  const refs = namedRefs(road);
  const total = segs.reduce((s, x) => s + x.km, 0);
  if (!total) return 0;
  return segs.filter((s) => onRoad(s, refs)).reduce((s, x) => s + x.km, 0) / total;
}

export function describeSeg(s: RoadSeg): string {
  return `${s.names.join(' / ') || '(unnamed)'} [${s.cls}${s.tunnel ? ', tunnel' : ''}] ${s.km.toFixed(1)} km @ ${s.lat.toFixed(3)}, ${s.lng.toFixed(3)}`;
}

/** Short fingerprint (FNV-1a) of a leg's encoded line, so tests can tell when legRoads.ts is stale. */
export function lineFingerprint(encoded: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < encoded.length; i++) {
    h ^= encoded.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, '0');
}
