/**
 * Road-snapped leg geometry, keyed "from>to" in clockwise order (see lib/geo.ts), as Google
 * encoded polylines (precision 5). GENERATED by `npm run snap-legs` — see scripts/snap-legs.ts.
 * Legs missing here are drawn as straight lines.
 */
export const LEG_GEOMETRY_SOURCE = 'none yet';
export const LEG_GEOMETRY: Record<string, string> = {};
